version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: vip
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
    driver: local
